version: '3'
services:
  app:
    container_name: birthdayy-dev
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ../src:/app/src
      - ../prisma:/app/prisma
    environment:
      - DOPPLER_TOKEN
    ports:
      - '4003:4000'
    depends_on:
      - redis
    networks:
    - global_dev

  redis: 
    container_name: birthdayy-dev-redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - global_dev

networks:
  global_dev:
