version: '3'
services:
  app:
    container_name: birthdayy-dev
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ../src:/app/src
      - ../prisma:/app/prisma
    environment:
      - DOPPLER_TOKEN
    ports:
      - '4003:4000'
    depends_on:
      - mysql
      - redis
    networks:
      - global_dev

  mysql:
    container_name: birthdayy-dev-mysql
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=birthdayy
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - global_dev
  influx:
    command: 'influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store bolt'
    container_name: birthdayy-dev-influxdb
    image: 'influxdb:2.7-alpine'
    networks:
      - global_dev
    ports:
      - '8285:8086'
    restart: always
    volumes:
      - 'influx-data:/var/lib/influxdb2'

  redis:
    container_name: birthdayy-dev-redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - global_dev

volumes:
  mysql-data:
    external: true
  influx-data:
    external: true
networks:
  global_dev:
