version: '3'
services:
  app:
    container_name: birthdayy
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      - DOPPLER_TOKEN
    ports:
      - '4003:4000'
