name: Deploy using Docker via SSH

on:
  workflow_call:
    inputs:
      DOCKER_TAG:
        description: 'Docker tag to deploy'
        type: string
        required: true
      DOPPLER_TOKEN:
        description: 'Doppler token'
        type: string
        required: true

jobs:
  ssh:
    name: SSH and deploy
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG: ${{ github.event.inputs.DOCKER_TAG }}
      DOPPLER_TOKEN: ${{ github.event.inputs.DOPPLER_TOKEN }}
    steps:
      - name: Login to GHCR.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER || github.actor }}
          password: ${{ secrets.GHCR_TOKEN || github.token }}

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: 'placeholder'

      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Run commands in remote host
        run: |
          ssh -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker stop ${{ github.event.repository.name }}-${{ env.DOCKER_TAG }} || true \\
          && docker rm ${{ github.event.repository.name }}-${{ secrets.DOCKER_TAG }} || true \\
          && docker image prune -a -f \\
          && docker run -d --restart=unless-stopped --net ${{ secrets.DOCKER_NETWORK }} --env DOPPLER_TOKEN=${{ env.DOPPLER_TOKEN }} --name ${{ github.event.repository.name }}-${{ env.DOCKER_TAG }} ghcr.io/$( echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]' ):${{ env.DOCKER_TAG || 'latest' }}"
