name: Node.js CI

on:
  push:
    branches: [production]
    paths:
      - 'src/**'
      - 'package.json'
      - 'yarn.lock'
  pull_request:
    branches: [develop, testing, production]
    paths:
      - 'src/**'
      - 'package.json'
      - 'yarn.lock'

jobs:
  build:
    uses: nikolaischunk/utilities/.github/workflows/node.js.yml@8d27ee0a9c5381380e0de3b76fc0c300886ff6e7
